export const GET_ALBUMS_START = 'GET_ALBUMS_START';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';

export const ADD_ALBUM_TO_FAVORITES = 'ADD_ALBUM_TO_FAVORITES';
export const REMOVE_ALBUM_FROM_FAVORITES = 'REMOVE_ALBUM_FROM_FAVORITES';
